export const countries = [
  {countryName: `Afghanistan`, countryCode: `AF`, currencyCode:`	AFN`},
  {countryName: `ALand Islands`, countryCode: `AX`, currencyCode:`		EUR`},
  {countryName: `Albania`, countryCode: `AL`, currencyCode:`ALL`},
  {countryName: `Algeria`, countryCode: `DZ`, currencyCode:`DZD`},
  {countryName: `American Samoa`, countryCode: `AS`, currencyCode:`USD`},
  {countryName: `Andorra`, countryCode: `AD`, currencyCode:`EUR`},
  {countryName: `Angola`, countryCode: `AO`, currencyCode:`AOA`},
  {countryName: `Anguilla`, countryCode: `AI`, currencyCode:`XCD`},
  {countryName: `Antarctica`, countryCode: `AQ`, currencyCode:`USD`},
  {countryName: `Antigua and Barbuda`, countryCode: `AG`, currencyCode:`XCD`},
  {countryName: `Argentina`, countryCode: `AR`, currencyCode:`ARS`},
  {countryName: `Armenia`, countryCode: `AM`, currencyCode:`AMD`},
  {countryName: `Aruba`, countryCode: `AW`, currencyCode:`AWG`},
  {countryName: `Ascension Island`, countryCode: `AC`, currencyCode:`SHP`},
  {countryName: `Australia`, countryCode: `AU`, currencyCode:`AUD`},
  {countryName: `Austria`, countryCode: `AT`, currencyCode:`EUR`},
  {countryName: `Azerbaijan`, countryCode: `AZ`, currencyCode:`AZN`},
  {countryName: `Bahamas`, countryCode: `BS`, currencyCode:`BSD`},
  {countryName: `Bahrain`, countryCode: `BH`, currencyCode:`BHD`},
  {countryName: `Bangladesh`, countryCode: `BD`, currencyCode:`BDT`},
  {countryName: `Barbados`, countryCode: `BB`, currencyCode:`BBD`},
  {countryName: `Belarus`, countryCode: `BY`, currencyCode:`BYN`},
  {countryName: `Belgium`, countryCode: `BE`, currencyCode:`EUR`},
  {countryName: `Belize`, countryCode: `BZ`, currencyCode:`BZD`},
  {countryName: `Benin`, countryCode: `BJ`, currencyCode:`XOF`},
  {countryName: `Bermuda`, countryCode: `BM`, currencyCode:`BMD`},
  {countryName: `Bhutan`, countryCode: `BT`, currencyCode:`INR`},
  {countryName: `Bolivia`, countryCode: `BO`, currencyCode:`BOB`},
  {countryName: `Bosnia and Herzegovina`, countryCode: `BA`, currencyCode:`BAM`},
  {countryName: `Botswana`, countryCode: `BW`, currencyCode:`BWP`},
  {countryName: `Bouvet Island`, countryCode: `BV`, currencyCode:`NOK`},
  {countryName: `Brazil`, countryCode: `BR`, currencyCode:`BRL`},
  {countryName: `British Indian Ocean Territory`, countryCode: `IO`, currencyCode:`USD`},
  {countryName: `British Virgin Islands`, countryCode: `VG`, currencyCode:`USD`},
  {countryName: `Brunei`, countryCode: `BN`, currencyCode:`BND`},
  {countryName: `Bulgaria`, countryCode: `BG`, currencyCode:`BGN`},
  {countryName: `Burkina Faso`, countryCode: `BF`, currencyCode:`XOF`},
  {countryName: `Burundi`, countryCode: `BI`, currencyCode:`BIF`},
  {countryName: `Cambodia`, countryCode: `KH`, currencyCode:`KHR`},
  {countryName: `Cameroon`, countryCode: `CM`, currencyCode:`XAF`},
  {countryName: `Canada`, countryCode: `CA`, currencyCode:`CAD`},
  {countryName: `Canary Islands`, countryCode: `IC`, currencyCode:`EUR`},
  {countryName: `Cape Verde`, countryCode: `CV`, currencyCode:`CVE`},
  {countryName: `Cayman Islands`, countryCode: `KY`, currencyCode:`KYD`},
  {countryName: `Central African Republic`, countryCode: `CF`, currencyCode:`XAF`},
  {countryName: `Chad`, countryCode: `TD`, currencyCode:`XAF`},
  {countryName: `Chile`, countryCode: `CL`, currencyCode:`CLP`},
  {countryName: `China`, countryCode: `CN`, currencyCode:`CNY`},
  {countryName: `Christmas Island`, countryCode: `CX`, currencyCode:`AUD`},
  {countryName: `Clipperton Island`, countryCode: `CC`, currencyCode:`AUD`},
  {countryName: `Colombia`, countryCode: `CO`, currencyCode:`COP`},
  {countryName: `Comoros`, countryCode: `KM`, currencyCode:`KMF`},
  {countryName: `Congo - Brazzaville`, countryCode: `CG`, currencyCode:`XAF`},
  {countryName: `Congo - Kinshasa`, countryCode: `CD`, currencyCode:`CDF`},
  {countryName: `Cook Islands`, countryCode: `CK`, currencyCode:`NZD`},
  {countryName: `Costa Rica`, countryCode: `CR`, currencyCode:`CRC`},
  {countryName: `Cote d’Ivoire`, countryCode: `CI	`, currencyCode:`XOF`},
  {countryName: `Croatia`, countryCode: `HR`, currencyCode:`HRK`},
  {countryName: `Cuba`, countryCode: `CU`, currencyCode:`CUP`},
  {countryName: `Curacao`, countryCode: `CW`, currencyCode:`ANG`},
  {countryName: `Cyprus`, countryCode: `CY`, currencyCode:`EUR`},
  {countryName: `Czech Republic`, countryCode: `CZ`, currencyCode:`CZK`},
  {countryName: `Denmark`, countryCode: `DK`, currencyCode:`DKK`},
  {countryName: `Djibouti`, countryCode: `DJ`, currencyCode:`DJF`},
  {countryName: `Dominica`, countryCode: `DM`, currencyCode:`XCD`},
  {countryName: `Dominican Republic`, countryCode: `DO`, currencyCode:`DOP`},
  {countryName: `East Timor`, countryCode: `TL`, currencyCode:`IDR`},
  {countryName: `Ecuador`, countryCode: `EC`, currencyCode:`USD`},
  {countryName: `Egypt`, countryCode: `EG`, currencyCode:`EGP`},
  {countryName: `El Salvador`, countryCode: `SV`, currencyCode:`SVC`},
  {countryName: `Equatorial Guinea`, countryCode: `GQ`, currencyCode:`XAF`},
  {countryName: `Eritrea`, countryCode: `ER`, currencyCode:`ERN`},
  {countryName: `Estonia`, countryCode: `EE`, currencyCode:`EUR`},
  {countryName: `Ethiopia`, countryCode: `ET`, currencyCode:`ETB`},
  {countryName: `Falkland Islands`, countryCode: `FK`, currencyCode:`FKP`},
  {countryName: `Faroe Islands`, countryCode: `FO`, currencyCode:`DKK`},
  {countryName: `Fiji`, countryCode: `FJ`, currencyCode:`FJD`},
  {countryName: `Finland`, countryCode: `FI`, currencyCode:`EUR`},
  {countryName: `France`, countryCode: `FR`, currencyCode:`EUR`},
  {countryName: `French Guiana`, countryCode: `GF`, currencyCode:`EUR`},
  {countryName: `French Polynesia`, countryCode: `PF`, currencyCode:`XPF`},
  {countryName: `French Southern Territories`, countryCode: `TF`, currencyCode:`EUR`},
  {countryName: `Gabon`, countryCode: `GA`, currencyCode:`XAF`},
  {countryName: `Gambia`, countryCode: `GM`, currencyCode:`GMD`},
  {countryName: `Georgia`, countryCode: `GE`, currencyCode:`GEL`},
  {countryName: `Germany`, countryCode: `DE`, currencyCode:`EUR`},
  {countryName: `Ghana`, countryCode: `GH`, currencyCode:`GHS`},
  {countryName: `Gibraltar`, countryCode: `GI`, currencyCode:`GIP`},
  {countryName: `Greece`, countryCode: `GR`, currencyCode:`EUR`},
  {countryName: `Greenland`, countryCode: `GL`, currencyCode:`DKK`},
  {countryName: `Grenada`, countryCode: `GD`, currencyCode:`XCD`},
  {countryName: `Guadeloupe`, countryCode: `GP`, currencyCode:`EUR`},
  {countryName: `Guam`, countryCode: `GU`, currencyCode:`USD`},
  {countryName: `Guatemala`, countryCode: `GT`, currencyCode:`GTQ`},
  {countryName: `Guernsey`, countryCode: `GG`, currencyCode:`GBP`},
  {countryName: `Guinea`, countryCode: `GN`, currencyCode:`GNF`},
  {countryName: `Guinea-Bissau`, countryCode: `GW`, currencyCode:`XOF`},
  {countryName: `Guyana`, countryCode: `GY`, currencyCode:`GYD`},
  {countryName: `Haiti`, countryCode: `HT`, currencyCode:`HTG`},
  {countryName: `Heard Island and McDonald Islands`, countryCode: `HM`, currencyCode:`AUD`},
  {countryName: `Honduras`, countryCode: `HN`, currencyCode:`HNL`},
  {countryName: `Hong Kong`, countryCode: `HK`, currencyCode:`HKD`},
  {countryName: `Hungary`, countryCode: `HU`, currencyCode:`HUF`},
  {countryName: `Iceland`, countryCode: `IS`, currencyCode:`ISK`},
  {countryName: `India`, countryCode: `IN`, currencyCode:`INR`},
  {countryName: `Indonesia`, countryCode: `ID`, currencyCode:`IDR`},
  {countryName: `Iran`, countryCode: `IR`, currencyCode:`IRR`},
  {countryName: `Iraq`, countryCode: `IQ`, currencyCode:`IQD`},
  {countryName: `Ireland`, countryCode: `IE`, currencyCode:`EUR`},
  {countryName: `Isle Of Man`, countryCode: `IM`, currencyCode:`GBP`},
  {countryName: `Israel`, countryCode: `IL`, currencyCode:`ILS`},
  {countryName: `Italy`, countryCode: `IT`, currencyCode:`EUR`},
  {countryName: `Jamaica`, countryCode: `JM`, currencyCode:`JMD`},
  {countryName: `Japan`, countryCode: `JP`, currencyCode:`JPY`},
  {countryName: `Jersey`, countryCode: `JE`, currencyCode:`GBP`},
  {countryName: `Jordan`, countryCode: `JO`, currencyCode:`JOD`},
  {countryName: `Kazakhstan`, countryCode: `KZ`, currencyCode:`KZT`},
  {countryName: `Kenya`, countryCode: `KE`, currencyCode:`KES`},
  {countryName: `Kiribati`, countryCode: `KI`, currencyCode:`AUD`},
  {countryName: `Kosovo`, countryCode: `XK`, currencyCode:`EUR`},
  {countryName: `Kuwait`, countryCode: `KW`, currencyCode:`KWD`},
  {countryName: `Kyrgyzstan`, countryCode: `KG`, currencyCode:`KGS`},
  {countryName: `Laos`, countryCode: `LA`, currencyCode:`LAK`},
  {countryName: `Latvia`, countryCode: `LV`, currencyCode:`EUR`},
  {countryName: `Lebanon`, countryCode: `LB`, currencyCode:`LBP`},
  {countryName: `Lesotho`, countryCode: `LS`, currencyCode:`LSL`},
  {countryName: `Liberia`, countryCode: `LR`, currencyCode:`LRD`},
  {countryName: `Libya`, countryCode: `LY`, currencyCode:`LYD`},
  {countryName: `Liechtenstein`, countryCode: `LI`, currencyCode:`CHF`},
  {countryName: `Lithuania`, countryCode: `LT`, currencyCode:`EUR`},
  {countryName: `Luxembourg`, countryCode: `LU`, currencyCode:`EUR`},
  {countryName: `Macau`, countryCode: `MO`, currencyCode:`MOP`},
  {countryName: `Macedonia`, countryCode: `MK`, currencyCode:`MKD`},
  {countryName: `Madagascar`, countryCode: `MG`, currencyCode:`MGA`},
  {countryName: `Malawi`, countryCode: `MW`, currencyCode:`MWK`},
  {countryName: `Malaysia`, countryCode: `MY`, currencyCode:`MYR`},
  {countryName: `Maldives`, countryCode: `MV`, currencyCode:`MVR`},
  {countryName: `Mali`, countryCode: `ML`, currencyCode:`XOF`},
  {countryName: `Malta`, countryCode: `MT`, currencyCode:`EUR`},
  {countryName: `Marshall Islands`, countryCode: `MH`, currencyCode:`USD`},
  {countryName: `Martinique`, countryCode: `MQ`, currencyCode:`EUR`},
  {countryName: `Mauritania`, countryCode: `MR`, currencyCode:`MRU`},
  {countryName: `Mauritius`, countryCode: `MU`, currencyCode:`MUR`},
  {countryName: `Mayotte`, countryCode: `YT`, currencyCode:`EUR`},
  {countryName: `Mexico`, countryCode: `MX`, currencyCode:`MXN`},
  {countryName: `Micronesia`, countryCode: `FM`, currencyCode:`USD`},
  {countryName: `Moldova`, countryCode: `MD`, currencyCode:`MDL`},
  {countryName: `Monaco`, countryCode: `MC`, currencyCode:`EUR`},
  {countryName: `Mongolia`, countryCode: `MN`, currencyCode:`MNT`},
  {countryName: `Montenegro`, countryCode: `ME`, currencyCode:`EUR`},
  {countryName: `Montserrat`, countryCode: `MS`, currencyCode:`XCD`},
  {countryName: `Morocco`, countryCode: `MA`, currencyCode:`MAD`},
  {countryName: `Mozambique`, countryCode: `MZ`, currencyCode:`MZN`},
  {countryName: `Myanmar`, countryCode: `MM`, currencyCode:`MMK`},
  {countryName: `NAMIBIA`, countryCode: `NA`, currencyCode:`NAD`},
  {countryName: `Nauru`, countryCode: `NR`, currencyCode:`AUD`},
  {countryName: `Nepal`, countryCode: `NP`, currencyCode:`NPR`},
  {countryName: `Netherlands`, countryCode: `NL`, currencyCode:`EUR`},
  {countryName: `Netherlands Antilles`, countryCode: `AN`, currencyCode:`ANG`},
  {countryName: `New Caledonia`, countryCode: `NC`, currencyCode:`XPF`},
  {countryName: `New Zealand`, countryCode: `NZ`, currencyCode:`NZD`},
  {countryName: `Nicaragua`, countryCode: `NI`, currencyCode:`NIO`},
  {countryName: `Niger`, countryCode: `NE`, currencyCode:`XOF`},
  {countryName: `Nigeria`, countryCode: `NG`, currencyCode:`NGN`},
  {countryName: `Niue`, countryCode: `NU`, currencyCode:`NZD`},
  {countryName: `Norfolk Island`, countryCode: `NF`, currencyCode:`AUD`},
  {countryName: `North Korea`, countryCode: `KP`, currencyCode:`KPW`},
  {countryName: `Northern Mariana Islands`, countryCode: `MP`, currencyCode:`USD`},
  {countryName: `Norway`, countryCode: `NO`, currencyCode:`NOK`},
  {countryName: `Oman`, countryCode: `OM`, currencyCode:`OMR`},
  {countryName: `Pakistan`, countryCode: `PK`, currencyCode:`PKR`},
  {countryName: `Palau`, countryCode: `PW`, currencyCode:`USD`},
  {countryName: `Palestine`, countryCode: `PS`, currencyCode:`JOD`},
  {countryName: `Panama`, countryCode: `PA`, currencyCode:`PAB`},
  {countryName: `Papua New Guinea`, countryCode: `PG`, currencyCode:`PGK`},
  {countryName: `Paraguay`, countryCode: `PY`, currencyCode:`PYG`},
  {countryName: `Peru`, countryCode: `PE`, currencyCode:`PEN`},
  {countryName: `Philippines`, countryCode: `PH`, currencyCode:`PHP`},
  {countryName: `Pitcairn`, countryCode: `PN`, currencyCode:`NZD`},
  {countryName: `Poland`, countryCode: `PL`, currencyCode:`PLN`},
  {countryName: `Portugal`, countryCode: `PT`, currencyCode:`EUR`},
  {countryName: `Puerto Rico`, countryCode: `PR`, currencyCode:`USD`},
  {countryName: `Qatar`, countryCode: `QA`, currencyCode:`QAR`},
  {countryName: `Reunion`, countryCode: `RE`, currencyCode:`EUR`},
  {countryName: `Romania`, countryCode: `RO`, currencyCode:`RON`},
  {countryName: `Rwanda`, countryCode: `RW`, currencyCode:`RWF`},
  {countryName: `Saint BarthÉLemy`, countryCode: `BL`, currencyCode:`EUR`},
  {countryName: `Saint Helena`, countryCode: `SH`, currencyCode:`GBP`},
  {countryName: `Saint Kitts and Nevis`, countryCode: `KN`, currencyCode:`XCD`},
  {countryName: `Saint Lucia`, countryCode: `LC`, currencyCode:`XCD`},
  {countryName: `Saint Martin (French Part)`, countryCode: `MF`, currencyCode:`EUR`},
  {countryName: `Saint Pierre and Miquelon`, countryCode: `PM`, currencyCode:`EUR`},
  {countryName: `Saint Vincent and the Grenadines`, countryCode: `VC`, currencyCode:`XCD`},
  {countryName: `Samoa`, countryCode: `WS`, currencyCode:`WST`},
  {countryName: `San Marino`, countryCode: `SM`, currencyCode:`EUR`},
  {countryName: `Sao Tome and Principe`, countryCode: `ST`, currencyCode:`STN`},
  {countryName: `Saudi Arabia`, countryCode: `SA`, currencyCode:`SAR`},
  {countryName: `Senegal`, countryCode: `SN`, currencyCode:`XOF`},
  {countryName: `Serbia`, countryCode: `RS`, currencyCode:`RSD`},
  {countryName: `Serbia and Montenegro`, countryCode: `CS`, currencyCode:`RSD`},
  {countryName: `Seychelles`, countryCode: `SC`, currencyCode:`SCR`},
  {countryName: `Sierra Leone`, countryCode: `SL`, currencyCode:`SLL`},
  {countryName: `Singapore`, countryCode: `SG`, currencyCode:`SGD`},
  {countryName: `Sint Maarten (Dutch Part)`, countryCode: `SX`, currencyCode:`ANG`},
  {countryName: `Slovakia`, countryCode: `SK`, currencyCode:`EUR`},
  {countryName: `Slovenia`, countryCode: `SI`, currencyCode:`EUR`},
  {countryName: `Solomon Islands`, countryCode: `SB`, currencyCode:`SBD`},
  {countryName: `Somalia`, countryCode: `SO`, currencyCode:`SOS`},
  {countryName: `South Africa`, countryCode: `ZA`, currencyCode:`ZAR`},
  {countryName: `South Georgia and the South Sandwich Islands`, countryCode: `GS`, currencyCode:`GBP`},
  {countryName: `South Korea`, countryCode: `KR`, currencyCode:`KRW`},
  {countryName: `South Sudan`, countryCode: `SS`, currencyCode:`SSP`},
  {countryName: `Spain`, countryCode: `ES`, currencyCode:`EUR`},
  {countryName: `Sri Lanka`, countryCode: `LK`, currencyCode:`LKR`},
  {countryName: `Sudan`, countryCode: `SD`, currencyCode:`SDG`},
  {countryName: `Svalbard and Jan Mayen`, countryCode: `SJ`, currencyCode:`NOK`},
  {countryName: `Swaziland`, countryCode: `SZ`, currencyCode:`SZL`},
  {countryName: `Sweden`, countryCode: `SE`, currencyCode:`SEK`},
  {countryName: `Switzerland`, countryCode: `CH`, currencyCode:`CHF`},
  {countryName: `Syria`, countryCode: `SY`, currencyCode:`SYP`},
  {countryName: `Taiwan`, countryCode: `TW`, currencyCode:`TWD`},
  {countryName: `Tajikistan`, countryCode: `TJ`, currencyCode:`TJS`},
  {countryName: `Tanzania`, countryCode: `TZ`, currencyCode:`TZS`},
  {countryName: `Thailand`, countryCode: `TH`, currencyCode:`THB`},
  {countryName: `Togo`, countryCode: `TG`, currencyCode:`XOF`},
  {countryName: `Tokelau`, countryCode: `TK`, currencyCode:`NZD`},
  {countryName: `Tonga`, countryCode: `TO`, currencyCode:`TOP`},
  {countryName: `Trinidad and Tobago`, countryCode: `TT`, currencyCode:`TTD`},
  {countryName: `Tristan da Cunha`, countryCode: `TA`, currencyCode:`SHP`},
  {countryName: `Tunisia`, countryCode: `TN`, currencyCode:`TND`},
  {countryName: `Turkey`, countryCode: `TR`, currencyCode:`TRY`},
  {countryName: `Turkmenistan`, countryCode: `TM`, currencyCode:`TMT`},
  {countryName: `Turks and Caicos Islands`, countryCode: `TC`, currencyCode:`USD`},
  {countryName: `Tuvalu`, countryCode: `TV`, currencyCode:`AUD`},
  {countryName: `U.S. Outlying Islands`, countryCode: `UM`, currencyCode:`USD`},
  {countryName: `U.S. Virgin Islands`, countryCode: `VI`, currencyCode:`USD`},
  {countryName: `Uganda`, countryCode: `UG`, currencyCode:`UGX`},
  {countryName: `Ukraine`, countryCode: `UA`, currencyCode:`UAH`},
  {countryName: `United Arab Emirates`, countryCode: `AE`, currencyCode:`AED`},
  {countryName: `United Kingdom`, countryCode: `GB`, currencyCode:`GBP`},
  {countryName: `United States`, countryCode: `US`, currencyCode:`USD`},
  {countryName: `Uruguay`, countryCode: `UY`, currencyCode:`UYU`},
  {countryName: `Uzbekistan`, countryCode: `UZ`, currencyCode:`UZS`},
  {countryName: `Vanuatu`, countryCode: `VU`, currencyCode:`VUV`},
  {countryName: `Vatican`, countryCode: `VA`, currencyCode:`EUR`},
  {countryName: `Venezuela`, countryCode: `VE`, currencyCode:`VES`},
  {countryName: `Vietnam`, countryCode: `VN`, currencyCode:`VND`},
  {countryName: `Wallis and Futuna`, countryCode: `WF`, currencyCode:`XPF`},
  {countryName: `Western Sahara`, countryCode: `EH`, currencyCode:`MAD`},
  {countryName: `Yemen`, countryCode: `YE`, currencyCode:`YER`},
  {countryName: `Zambia`, countryCode: `ZM`, currencyCode:`ZMW`},
  {countryName: `Zimbabwe`, countryCode: `ZW`, currencyCode:`ZWL`},
]